[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal-cf/brokerapi"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-community/go-credhub"
